#%Module

prereq yasp

# setenv ALIAN_DIR {{yasp_dir}}
setenv ALIAN_DIR {{prefix}}
setenv ALIAN_SRC {{yasp.alian_dir}}
setenv ALIAN_DEV {{yasp.alian_dir}}
setenv ALIAN_PREFIX {{prefix}}
setenv ALIAN_PYTHON_LIB {{prefix}}/lib
prepend-path PATH {{prefix}}/bin
prepend-path LD_LIBRARY_PATH {{prefix}}/lib
prepend-path DYLD_LIBRARY_PATH {{prefix}}/lib
prepend-path PYTHONPATH {{prefix}}/lib
prepend-path PYTHONPATH {{prefix}}/lib/{{python_site_packages_subpath}}
set-alias ALIAN_cd "cd {{yasp.alian_dir}}"
prepend-path CPATH {{prefix}}/include
