# Event cuts
selections:
  event:
    event_sel: selMC
    rct: CBT
  track:
    pt_min: 0.150
    track_sel: globalTrack

# remove the jet_finder section below if jets are not needed in analysis
jet_finder:
  R: 0.4
  alg: antikt
  pT_min: 10

analysis:
  pt_min_eec: 1.0

output:
  bins:
    jet_pT: ['lin', 0, 200, 200]
    RL: ['log', 1.0e-2, 0.4, 20]
  histograms:
    jet_pT_det: [1, "jet_pT_det", "Det. jet #it{p}_{T} spectrum;jet #it{p}_{T} (GeV);Counts", jet_pT]
    jet_pT_gen: [1, "jet_pT_gen", "Gen. jet #it{p}_{T} spectrum;jet #it{p}_{T} (GeV);Counts", jet_pT]
    eec_T_det: [2, "eec_T_det", "EEC_T (det);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_T_gen: [2, "eec_T_gen", "EEC_T (gen);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_P_det: [2, "eec_P_det", "EEC_P (det);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_P_gen: [2, "eec_P_gen", "EEC_P (gen);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_M_det: [2, "eec_M_det", "EEC_M (det);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_M_gen: [2, "eec_M_gen", "EEC_M (gen);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_PM_det: [2, "eec_PM_det", "EEC_PM (det);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_PM_gen: [2, "eec_PM_gen", "EEC_PM (gen);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_det: [2, "eec_Q_det", "EEC_Q (det);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_gen: [2, "eec_Q_gen", "EEC_Q (gen);jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
