# Event cuts
selections:
  event:
    event_sel: selMC
    rct: CBT
  track:
    pt_min: 0.150
    track_sel: globalTrack

# remove the jet_finder section below if jets are not needed in analysis
jet_finder:
  R: 0.4
  alg: antikt
  pT_min: 5

analysis:
  pt_min_eec: 1.0

output:
  bins:
    # jet_pT: ['lin', 10, 150, 14]
    jet_pT: ['c', [5, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, 120, 130, 140, 150]]
    RL: ['log', 1.0e-2, 0.4, 20]
    ew: ['log', 1.0e-6, 1, 15]
  histograms:
    # eec_T_det: [3, "eec_T_det", "EEC T det", RL, ew, jet_pT]
    # eec_P_det: [3, "eec_P_det", "EEC P det", RL, ew, jet_pT]
    # eec_M_det: [3, "eec_M_det", "EEC P det", RL, ew, jet_pT]
    # eec_PM_det: [3, "eec_PM_det", "EEC P det", RL, ew, jet_pT]
    # eec_T_gen: [3, "eec_T_gen", "EEC T gen", RL, ew, jet_pT]
    # eec_P_gen: [3, "eec_P_gen", "EEC P gen", RL, ew, jet_pT]
    # eec_M_gen: [3, "eec_M_gen", "EEC P gen", RL, ew, jet_pT]
    # eec_PM_gen: [3, "eec_PM_gen", "EEC P gen", RL, ew, jet_pT]
    # jet_pT_resp: [2, "jet_pT_resp", "Jet #it{p}_{T} response matrix;det. jet #it{p}_{T} (GeV);gen. jet #it{p}_{T} (GeV)", jet_pT, jet_pT]
  responses:
    eec_T_unf: [3, "eec_T_unf", "EEC T response matrix", RL, ew, jet_pT, RL, ew, jet_pT]
    eec_P_unf: [3, "eec_P_unf", "EEC P response matrix", RL, ew, jet_pT, RL, ew, jet_pT]
    eec_M_unf: [3, "eec_M_unf", "EEC P response matrix", RL, ew, jet_pT, RL, ew, jet_pT]
    eec_PM_unf: [3, "eec_PM_unf", "EEC P response matrix", RL, ew, jet_pT, RL, ew, jet_pT]
    # eec_unf: [3, "eec_unf", "EEC pair response matrix", ew, RL, jet_pT, ew, RL, jet_pT]