trk_eta_max: 0.9
photon_eta_max: 0.7

trk_pT_min: 0.15
trk_pT_max: 100
photon_pT_min: 15
jet_pT_min: 5.0

isocone_R: 0.4
isocone_pT_max: 1.5
photon_jet_dphi_min: 0.75

jetR: 0.4
jet_matching_fraction: 0.6

thr: 1.0
RL_binning: [1.0E-3, 1, 30] # the period is important as otherwise PyYAML will read it as a string
pT_binning: [0, 200, 200]
photon_pT_binning: [0, 400, 400]

scale_hists: True