constants:
  pi34: &pi34 2.35619449019
  # pi78: &pi78 2.74889357189
  # halfpi: &pihalf 1.57079632679
  # pi: &pi 3.14159265359

# Event cuts
selections:
  event:
    event_sel: sel8
    trig_sel: GammaHighPtEMCAL, GammaHighPtDCAL
    rct: CBT_calo
  track:
    pt_min: 0.150
    track_sel: globalTrack
  cluster:
    energy_min: 0.7
    m02_min: none
    m02_max: none
    ncells_min: 2
    time_min: -30
    time_max: 35
    exoticity: True
    nlm: 2
    defn: 0
    edge: True
    delta_phi: 0.05
    delta_eta: 0.05
    ep_max: 1.75
  isolation:
    iso_pt_max: 1.5

jet_finder:
  R: 0.4
  alg: antikt
  pT_min: 10

analysis:
  cluster_pt_min: 10
  photon_jet_angle_min: *pi34
  pt_min_eec: 1.0
  params: [66.234448, 11.20858432, 0.19343861, 21.31815129, 7.55079534]
  m02_narrow_min: 0.1
  m02_narrow_max: 0.3
  m02_wide_min: 0.4
  m02_wide_max: 20

output:
  bins:
    jet_pT: ['lin', 0, 200, 200]
    RL: ['log', 1.0e-3, 1, 30]
  histograms:
    jet_pT_narrow: [1, "jet_pT_narrow", "Jet #it{p}_{T} spectrum;jet #it{p}_{T} (GeV);Counts", jet_pT]
    jet_pT_wide: [1, "jet_pT_wide", "Jet #it{p}_{T} spectrum;jet #it{p}_{T} (GeV);Counts", jet_pT]
    photon_pT_narrow: [1, "photon_pT_narrow", "Photon #it{p}_{T} spectrum;photon #it{p}_{T} (GeV);Counts", jet_pT]
    photon_pT_wide: [1, "photon_pT_wide", "Photon #it{p}_{T} spectrum;photon #it{p}_{T} (GeV);Counts", jet_pT]
    eec_T_narrow:  [2, "eec_T_narrow",  "Photon-tagged EEC_T;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_P_narrow:  [2, "eec_P_narrow",  "Photon-tagged EEC_P;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_M_narrow:  [2, "eec_M_narrow",  "Photon-tagged EEC_M;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_PM_narrow: [2, "eec_PM_narrow", "Photon-tagged EEC_PM;jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_narrow:  [2, "eec_Q_narrow",  "Photon-tagged EEC_Q;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_T_wide:  [2, "eec_T_wide",  "Photon-tagged EEC_T;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_P_wide:  [2, "eec_P_wide",  "Photon-tagged EEC_P;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_M_wide:  [2, "eec_M_wide",  "Photon-tagged EEC_M;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]
    eec_PM_wide: [2, "eec_PM_wide", "Photon-tagged EEC_PM;jet #it{p}_{T} (GeV);#it{R}_{L}", jet_pT, RL]
    eec_Q_wide:  [2, "eec_Q_wide",  "Photon-tagged EEC_Q;jet #it{p}_{T} (GeV);#it{R}_{L}",  jet_pT, RL]

